name: Docker Build and Push

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Ключевое разрешение!
      id-token: write  # Для OIDC аутентификации
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Автоматическое имя пользователя
          password: ${{ secrets.GITHUB_TOKEN }}  # Используем встроенный токен
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mura-rj/pet-app:latest
            ghcr.io/mura-rj/pet-app:${{ github.sha }}
          # Явно указываем видимость пакета
          visibility: public  # Или 'private' если нужно
